//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class addtocart
    {
        public int cartid { get; set; }
        public Nullable<int> productid { get; set; }
        [Required(ErrorMessage = "quantity is required")]
        public Nullable<int> quantity { get; set; }
        public Nullable<double> amount { get; set; }
       
        public virtual product product { get; set; }

        internal static decimal Sum(Func<object, object> value)
        {
            throw new NotImplementedException();
        }
    }
}
