//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public int adminid { get; set; }
        public string adminname { get; set; }
        [Required(ErrorMessage = "username is required")]
        public string username { get; set; }
        [Required(ErrorMessage = "password is required")]
        public string password { get; set; }
    }
}
