//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        public int customerid { get; set; }
        [Required(ErrorMessage = "username is required")]
        public string username { get; set; }
        [Required(ErrorMessage = "password is required")]
        public string password { get; set; }
        public string fullname { get; set; }
        public string emailid { get; set; }
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?[0-9]{3}\)?[-.]?([0-9]{3})[-.]?([0-9]{4})$", ErrorMessage = "Not a valid Number")]
        public string phonenumber { get; set; }
        public string address { get; set; }
        public string pincode { get; set; }
    }
}
